
name: CI/CD Docker Microservicio Flask (GHCR)

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/my_flask_app:main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Login en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir y publicar imagen
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar por SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | sudo docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            sudo docker pull ghcr.io/${{ github.repository_owner }}/my_flask_app:main
            sudo docker rm -f flask-api || true
            sudo docker run -d --name flask-api --restart unless-stopped -p 5000:5000 ghcr.io/${{ github.repository_owner }}/my_flask_app:main
            sudo docker ps